name: Image Upload

# branch master일 때만 액션 실행
on:
  push:
    branches: [ "master" ]

jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v4 # first action : checkout source code
    - name: registry login
      run: | # log into docker hub account
        docker build . --file Dockerfile --tag registry.andongh.com/${{secrets.IMAGE_NAME}}/${{secrets.IMAGE_NAME}}:latest
        docker push registry.andongh.com/${{secrets.IMAGE_NAME}}/${{secrets.IMAGE_NAME}}:latest